/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bicho9.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/bicho9.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material}  position={[0,0,1]} scale={0.55} rotation={[-1.5,0,0]} />
    </group>
  )
}

useGLTF.preload('/bicho9.glb')

export default Model
